top_dir = ../..

src_module = counter_tb
src_files = $(src_module).v

# command-line arguments for Verilog simulator
CVER_FLAGS =
IVL_FLAGS =
VCS_FLAGS =
VSIM_FLAGS =

include $(top_dir)/examples/template.mk
