RUBY_VPI_PATH = '../..'

SIMULATOR_SOURCES = FileList['*.v']
SIMULATOR_TARGET = 'counter_runner'
SIMULATOR_ARGS = {
	:cver => nil,
	:ivl => nil,
	:vcs => nil,
	:vsim => nil,
}

load "#{RUBY_VPI_PATH}/examples/template.rake"
