RUBY_VPI_PATH = '../..'

SIMULATOR_SOURCES = FileList['*.v']
SIMULATOR_TARGET = 'counter_runner'
SIMULATOR_ARGS = {
	:cver => '',
	:ivl => '',
	:vcs => '',
	:vsim => '',
}

load "#{RUBY_VPI_PATH}/examples/template.rake"
