=begin
  Copyright 2006 Suraj N. Kurapati

  This file is part of Ruby-VPI.

  Ruby-VPI is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  Ruby-VPI is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Ruby-VPI; if not, write to the Free Software Foundation,
  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
=end

require 'rake/clean'
require 'doc_proxy'
require 'doc_format'

FileList['*.erb'].each do |src|
  prefix = File.basename(src, '.erb')
  helper = prefix + '.rb'
  dst = prefix + '.html'

  desc "Process file #{src.inspect}."
  file dst => [src, 'common.tpl'] do |t|
    # process the documentation source file
      proxy = DocProxy.new(File.read(src))

      # set default configuration
        @table_of_contents = true
        @title = nil

      content = proxy.instance_eval do
        if File.exist? helper
          instance_eval File.read(helper)
        end

        result(binding)
      end

    # store result using common HTML template
      template = ERB.new(File.read(t.prerequisites[1]))
      content = template.result(binding)

      File.open(dst, 'w') do |f|
        f << content
      end

      puts "wrote #{dst.inspect}"
  end

  task :default => dst
end

CLOBBER.include '*.html'
